// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PilgrimFinalDmv.Models;

namespace PilgrimFinalDmv.Data;

public partial class pilgrimfinalContext : DbContext
{
    public pilgrimfinalContext(DbContextOptions<pilgrimfinalContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Driver> Drivers { get; set; }

    public virtual DbSet<DriverInfraction> DriverInfractions { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Driver>(entity =>
        {
            entity.HasKey(e => e.SocialNumber).HasName("PK__Drivers__B98AC50390B1EEA0");

            entity.Property(e => e.SocialNumber)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DepartmentId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("DepartmentID");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.PlateNumber)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Vin)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("VIN");
        });

        modelBuilder.Entity<DriverInfraction>(entity =>
        {
            entity.HasKey(e => e.InfractionId).HasName("PK__DriverIn__66F5B697A9BC7454");

            entity.Property(e => e.InfractionId).HasColumnName("InfractionID");
            entity.Property(e => e.DepartmentId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("DepartmentID");
            entity.Property(e => e.Infraction)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.SocialNumber)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PK__Employee__7AD04FF16EBB3C20");

            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.DepartmentId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("DepartmentID");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}