// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PilgrimFinal.Models;

namespace PilgrimFinal.Data;

public partial class pilgrim_dmvContext : DbContext
{
    public pilgrim_dmvContext(DbContextOptions<pilgrim_dmvContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Driver> Drivers { get; set; }

    public virtual DbSet<DriverInfraction> DriverInfractions { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Driver>(entity =>
        {
            entity.HasKey(e => e.SocialNumber).HasName("PK__Drivers__166A97FB23DA7D41");

            entity.Property(e => e.SocialNumber)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Social_Number");
            entity.Property(e => e.EmployeeId)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Employee_ID");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("First_Name");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Last_Name");
            entity.Property(e => e.PlateNumber)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Plate_Number");
            entity.Property(e => e.Vin)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("VIN");
        });

        modelBuilder.Entity<DriverInfraction>(entity =>
        {
            entity.HasKey(e => e.InfractionId).HasName("PK__Driver_I__66F5B6977F75D20B");

            entity.ToTable("Driver_Infractions");

            entity.Property(e => e.InfractionId).HasColumnName("InfractionID");
            entity.Property(e => e.BadgeNumber)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Badge_Number");
            entity.Property(e => e.Infraction)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.SocialNumber)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Social_Number");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PK__Employee__7AD04FF17CFDB532");

            entity.ToTable("Employee");

            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.BadgeNumber)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Badge_Number");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("First_Name");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Last_Name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}