// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PilgrimFinalDmv.Models;

public partial class DriverInfraction
{
    public int InfractionId { get; set; }

    public string SocialNumber { get; set; }

    public string DepartmentId { get; set; }

    public string Infraction { get; set; }
}