// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PilgrimFinal.Models;

public partial class Driver
{
    public string SocialNumber { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string PlateNumber { get; set; }

    public string Vin { get; set; }

    public string EmployeeId { get; set; }
}