// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PilgrimFinal.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string BadgeNumber { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }
}